portals:
    portal1:
        location:
            1:
                x: 0
                y: 0
                z: 0
            2:
                x: 0
                y: 0
                z: 0
            world: world
        permission: RiotPortals.portal1
        server: portal1

debug: false